import ContextProvider from "./pages/set-product/context-provider";
import Header from "./header";
import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <ContextProvider>
          
          <Header/>
          
          <main>
            {children}
          </main>

          <footer>
            
          </footer>

        </ContextProvider>
      </body>
    </html>
  )
}
